export const icons = [
    {'ligadura': 'plus'},
    {'ligadura': 'dialog'},
    {'ligadura': 'generic_document'},
    {'ligadura': 'xls'},
    {'ligadura': 'filter'},
    {'ligadura': 'hierachy'},
    {'ligadura': 'minus'},
    {'ligadura': 'sectors'},
    {'ligadura': 'user_hierachy'},
    {'ligadura': 'down_arrow_line'},
    {'ligadura': 'left_arrow_line'},
    {'ligadura': 'right_arrow_line'},
    {'ligadura': 'up_arrow_line'},
    {'ligadura': 'more_vert'},
    {'ligadura': 'archive'},
    {'ligadura': 'unarchive'},
    {'ligadura': 'chat'},
    {'ligadura': 'attach'},
    {'ligadura': 'path_finder'},
    {'ligadura': 'pdf'},
    {'ligadura': 'send_form'},
    {'ligadura': 'alert'},
    {'ligadura': 'app_qr'},
    {'ligadura': 'bike'},
    {'ligadura': 'bike_code'},
    {'ligadura': 'bike_cover'},
    {'ligadura': 'blockchain'},
    {'ligadura': 'calefaction'},
    {'ligadura': 'car'},
    {'ligadura': 'car_b'},
    {'ligadura': 'car_bl'},
    {'ligadura': 'car_br'},
    {'ligadura': 'car_cover'},
    {'ligadura': 'car_f'},
    {'ligadura': 'car_fl'},
    {'ligadura': 'car_fr'},
    {'ligadura': 'card'},
    {'ligadura':'clean_bike'},
    {'ligadura':'clean_car'},
    {'ligadura':'clean_motorbike'},
    {'ligadura':'clock'},
    {'ligadura':'close'},
    {'ligadura':'cloud_v2'},
    {'ligadura':'computers'},
    {'ligadura':'config'},
    {'ligadura':'config_ok'},
    {'ligadura':'contract'},
    {'ligadura':'cop'},
    {'ligadura':'cpu'},
    {'ligadura':'credential'},
    {'ligadura':'date'},
    {'ligadura':'desk'},
    {'ligadura':'digital_signature'},
    {'ligadura':'dishwhasher'},
    {'ligadura':'down'},
    {'ligadura':'download_pdf'},
    {'ligadura':'false'},
    {'ligadura':'finished'},
    {'ligadura':'folder'},
    {'ligadura':'fridge'},
    {'ligadura':'history'},
    {'ligadura':'joystick'},
    {'ligadura':'left'},
    {'ligadura':'login'},
    {'ligadura':'logout'},
    {'ligadura':'loundry_calefaction'},
    {'ligadura':'mail'},
    {'ligadura':'microwave'},
    {'ligadura':'motorbike_b'},
    {'ligadura':'motorbike'},
    {'ligadura':'motorbike_cover'},
    {'ligadura':'motorbike_fl'},
    {'ligadura':'movements'},
    {'ligadura':'new_document'},
    {'ligadura':'night'},
    {'ligadura':'notebook'},
    {'ligadura':'notification'},
    {'ligadura':'oven'},
    {'ligadura':'ovens'},
    {'ligadura':'p2p_dfs'},
    {'ligadura':'phone'},
    {'ligadura':'photo'},
    {'ligadura':'photo_history'},
    {'ligadura':'photo_session'},
    {'ligadura':'place'},
    {'ligadura':'plate'},
    {'ligadura':'policy_qr'},
    {'ligadura':'printer'},
    {'ligadura':'procedures'},
    {'ligadura':'reload'},
    {'ligadura':'reminder'},
    {'ligadura':'report'},
    {'ligadura':'resize'},
    {'ligadura':'right'},
    {'ligadura':'rim'},
    {'ligadura':'search'},
    {'ligadura':'share'},
    {'ligadura':'shield'},
    {'ligadura':'speaker'},
    {'ligadura':'sun'},
    {'ligadura':'time'},
    {'ligadura':'top'},
    {'ligadura':'touch'},
    {'ligadura':'transfer'},
    {'ligadura':'trash'},
    {'ligadura':'true'},
    {'ligadura':'tv'},
    {'ligadura':'tv_video'},
    {'ligadura':'upload'},
    {'ligadura':'upload_v2'},
    {'ligadura':'user'},
    {'ligadura':'user_details'},
    {'ligadura':'valid_place'},
    {'ligadura':'video'},
    {'ligadura':'view'},
    {'ligadura':'washing_machine'},
    {'ligadura':'wheel'},
    {'ligadura':'white_appliance'},
    {'ligadura':'win'},
    {'ligadura':'wine_cellar'},

]

